# TCL File Generated by Component Editor 18.1
# Fri Nov 15 20:56:14 CST 2019
# DO NOT MODIFY


# 
# avalon_blitter "avalon_blitter" v1.0
#  2019.11.15.20:56:14
# 
# 

# 
# request TCL package from ACDS 16.1
# 
package require -exact qsys 16.1


# 
# module avalon_blitter
# 
set_module_property DESCRIPTION ""
set_module_property NAME avalon_blitter
set_module_property VERSION 1.0
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property AUTHOR ""
set_module_property DISPLAY_NAME avalon_blitter
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property REPORT_TO_TALKBACK false
set_module_property ALLOW_GREYBOX_GENERATION false
set_module_property REPORT_HIERARCHY false


# 
# file sets
# 
add_fileset QUARTUS_SYNTH QUARTUS_SYNTH "" ""
set_fileset_property QUARTUS_SYNTH TOP_LEVEL new_component
set_fileset_property QUARTUS_SYNTH ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property QUARTUS_SYNTH ENABLE_FILE_OVERWRITE_MODE false
add_fileset_file avalon_blitter_interface.sv SYSTEM_VERILOG PATH avalon_blitter_interface.sv TOP_LEVEL_FILE

add_fileset SIM_VERILOG SIM_VERILOG "" ""
set_fileset_property SIM_VERILOG ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property SIM_VERILOG ENABLE_FILE_OVERWRITE_MODE false
add_fileset_file avalon_blitter_interface.sv SYSTEM_VERILOG PATH avalon_blitter_interface.sv


# 
# parameters
# 


# 
# display items
# 


# 
# connection point clk
# 
add_interface clk clock end
set_interface_property clk clockRate 50000000
set_interface_property clk ENABLED true
set_interface_property clk EXPORT_OF ""
set_interface_property clk PORT_NAME_MAP ""
set_interface_property clk CMSIS_SVD_VARIABLES ""
set_interface_property clk SVD_ADDRESS_GROUP ""

add_interface_port clk CLOCK clk Input 1


# 
# connection point s1
# 
add_interface s1 avalon end
set_interface_property s1 addressUnits WORDS
set_interface_property s1 associatedClock clk
set_interface_property s1 associatedReset RESET
set_interface_property s1 bitsPerSymbol 8
set_interface_property s1 burstOnBurstBoundariesOnly false
set_interface_property s1 burstcountUnits WORDS
set_interface_property s1 explicitAddressSpan 0
set_interface_property s1 holdTime 0
set_interface_property s1 linewrapBursts false
set_interface_property s1 maximumPendingReadTransactions 0
set_interface_property s1 maximumPendingWriteTransactions 0
set_interface_property s1 readLatency 0
set_interface_property s1 readWaitStates 0
set_interface_property s1 readWaitTime 0
set_interface_property s1 setupTime 0
set_interface_property s1 timingUnits Cycles
set_interface_property s1 writeWaitTime 0
set_interface_property s1 ENABLED true
set_interface_property s1 EXPORT_OF ""
set_interface_property s1 PORT_NAME_MAP ""
set_interface_property s1 CMSIS_SVD_VARIABLES ""
set_interface_property s1 SVD_ADDRESS_GROUP ""

add_interface_port s1 AVL_ADDR address Input 5
add_interface_port s1 AVL_READ read Input 1
add_interface_port s1 AVL_WRITE write Input 1
add_interface_port s1 AVL_CS chipselect Input 1
add_interface_port s1 AVL_READDATA readdata Output 32
add_interface_port s1 AVL_WRITEDATA writedata Input 32
add_interface_port s1 AVL_BYTE_EN byteenable Input 4
set_interface_assignment s1 embeddedsw.configuration.isFlash 0
set_interface_assignment s1 embeddedsw.configuration.isMemoryDevice 0
set_interface_assignment s1 embeddedsw.configuration.isNonVolatileStorage 0
set_interface_assignment s1 embeddedsw.configuration.isPrintableDevice 0


# 
# connection point Export
# 
add_interface Export conduit end
set_interface_property Export associatedClock clk
set_interface_property Export associatedReset RESET
set_interface_property Export ENABLED true
set_interface_property Export EXPORT_OF ""
set_interface_property Export PORT_NAME_MAP ""
set_interface_property Export CMSIS_SVD_VARIABLES ""
set_interface_property Export SVD_ADDRESS_GROUP ""

add_interface_port Export EXPORT_DATA new_signal Output 9
add_interface_port Export EXPORT_TEST new_signal_1 Output 32
add_interface_port Export Data_to_Blitter new_signal_2 Output 64
add_interface_port Export Blitter_Finish_Flip new_signal_3 Input 1
add_interface_port Export Status_REG_Out new_signal_4 Output 1


# 
# connection point RESET
# 
add_interface RESET reset end
set_interface_property RESET associatedClock clk
set_interface_property RESET synchronousEdges DEASSERT
set_interface_property RESET ENABLED true
set_interface_property RESET EXPORT_OF ""
set_interface_property RESET PORT_NAME_MAP ""
set_interface_property RESET CMSIS_SVD_VARIABLES ""
set_interface_property RESET SVD_ADDRESS_GROUP ""

add_interface_port RESET Hard_RESET reset Input 1

